name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./Server/Sources

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: somka4docker
        password: 5b14fc43-01a9-41ad-b688-6f8b52681f0d
    - name: Build and push Docker images
          # You may pin to the exact commit or the version.
          # uses: docker/build-push-action@9379083e426e2e84abb80c8c091f5cdeb7d3fd7a
      uses: docker/build-push-action@v2.3.0
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: ./Sources
        # Path to the Dockerfile
        file: ./Docker/.dockerfile
        # List of build-time variables
        build-args: "-t somka4docker/intelpos"
        # List of tags
        tags: latest
        # Push is a shorthand for --output=type=registry
        push: true
